# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iyS8EwI0kXIfTLIXmq/z69BnaCjt84qNKFuBwucdMFeZ91hw6gB0gryZ2GcVq7ezN2FygoiEfA9UkPPIA/z5S52W3aVJBlLljNh/4P5D8W2RxXQHfbEczZHAWHT2IjySE2k76C9qcmhTNngEq/YPzCMPYdRctf2R3yRaFd6ZsldDG0NMUtRKIx+WEHs9MZv5hAwqerf8YV9l2RoBPIwjgp+YNal/K1C/zj9ktL+OQ7HvNL3Q194ysYapFIvtNjusJQPZ1k5Uz2CpNc/fZPhQxKJ2TBKanh0es2nHUTvRfZibcyL44APIfrYKKHHDyQmDiifnHkeEI2Oq9oYF1K24ZrUZiMzumDxmDtkzBIfWy/t4Gpmt0tOTeT6h9hCn4XqMOj6rfnnuInou8MwC0TLLpYh60769b+W4q/kRlM1UQK55HPTr6CYjVZ2iJWphClEKc/058tKHFkyP7bp9i+lwxhAwwgk0UHt+A/fTcXHVflkCQ195lr9AZGHSD1HJPWMbmERoTBb4978V1r7ojAaQSxo/x57cxgB4uSVHtZygEQlv5KpyHTyz2cTQOQBU4GQ4E7KYXDYIoUL4vcb/MK10wKg9ftiXUIwxPzGTnBLWULsYVQWjXImBInyIcdcaIwB2FLXualRGEhGeZkkDaRxgY0anzqFEH77Yoj2ve8LQ2S8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
