travis:
  secure:
    BINSTAR_TOKEN: NF+hEPkyryI4m/qsw/0nba2gn4BRHNSRfYr9jxdEf7EdPkLmJYSQNZTJ5l9ffAd2grQvl7J+JtlEMKucnko2nDcypWMrG67yAg7964mWdxxofjjMe+jDqRk0pZ1zqG+warJd4RbZJlVZilIRENNLX2QBgNusdhb44wbQUMLoiWjhrBy4u83mkrWBCA6IQTWSpNrGu4NF95Xxtx8YB3UU4afw58HIRYYZxZ6yYnaDPk1SHyee76g0+y0yc2ygQdvoGuODIx7fCuE+PUj8cLvBToadIu34qu8VJYowpQmi/xjs2hUqRR8nbVXOL+jtxp2DDqHPOC3SenG1PI726eRZjuH5LL7sgjLMgLcLDq8rkHr+KXZwSu9lkMlHRRwD9iYeu9oyXdw747IWJtRWzhM9ZK3e2sHrfURk04bpEy+AaP7sgtPXFehyBzBdJuOFdeYF9cPbpKYZvMdOISAH8CSf3wx+8aOW3bE5rOXHTsg2WgG2SqPUeB0SJKUJvOk3AW0TQ5nj1fTXF6Sl45VweKInHz8M1+/R56ayqtKZS9DCQ6XKxBGTtZX+6fwCVELPSAtAvcLxTT0sUt4QqggIVZSkGIYteW1qayHIn9pY+VeuWnWzOKsWHrPWKMcfQyOfq/XaseF1pyYkElW+FqVzEMMPeG5lkNuYDt97dXx9IlCwqyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
